# -*- coding: utf-8 -*-
"""AIagent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cmxi0hgU_Cv9Y_wYsinHoKNjQOYRzUoE
"""

import sqlite3
import pandas as pd
from openai import OpenAI
import os

from google.colab import userdata
from openai import OpenAI

client = OpenAI(
    api_key=userdata.get("SQL_KEY"),   # 👈 must match EXACTLY
    base_url="https://api.groq.com/openai/v1"
)

# ------------------ DATABASE ------------------
conn = sqlite3.connect("chinook.db")
cursor = conn.cursor()

# ------------------ GET TABLES ------------------
def get_tables():
    tables = cursor.execute(
        "SELECT name FROM sqlite_master WHERE type='table';"
    ).fetchall()
    return [t[0] for t in tables]

# ------------------ GET SCHEMA ------------------
def get_schema(tables):
    schema = ""
    for table in tables:
        cols = cursor.execute(f"PRAGMA table_info({table});").fetchall()
        schema += f"\nTable {table}: "
        for col in cols:
            schema += f"{col[1]}, "
    return schema

# ------------------ GENERATE SQL ------------------
def generate_sql(question):
    tables = get_tables()
    schema = get_schema(tables)

    prompt = f"""
You are an expert SQL generator for SQLite.

IMPORTANT RULES:
- Use ONLY the tables provided
- DO NOT invent table names
- ONLY return SQL query
- DO NOT explain anything

Schema:
{schema}

Question:
{question}
"""

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    sql = response.choices[0].message.content.strip()

    # Clean SQL if model adds formatting
    sql = sql.split("```")[-1] if "```" in sql else sql
    sql = sql.replace("sql", "").strip()

    return sql

# ------------------ FIX SQL ------------------
def fix_sql(query, error):
    prompt = f"""
Fix this SQL query based on error.

Query:
{query}

Error:
{error}

Return ONLY corrected SQL.
"""

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    fixed = response.choices[0].message.content.strip()
    fixed = fixed.replace("```", "").strip()

    return fixed

# ------------------ RUN QUERY ------------------
def run_query(sql):
    try:
        df = pd.read_sql_query(sql, conn)
        return df
    except Exception as e:
        return f"Error: {str(e)}"

# ------------------ MAIN AGENT ------------------
def ask_agent(question):
    print("\n==============================")
    print(f"QUESTION: {question}")

    # Step 1: Generate SQL
    sql = generate_sql(question)
    print("\n🔹 Generated SQL:")
    print(sql)

    # Step 2: Run query
    result = run_query(sql)

    # Step 3: Auto-fix if error
    if isinstance(result, str) and "Error" in result:
        print("\n⚠️ Fixing query...")

        fixed_sql = fix_sql(sql, result)
        print("\n🔹 Fixed SQL:")
        print(fixed_sql)

        result = run_query(fixed_sql)

    # Step 4: Display result
    print("\n🔹 Result:\n")

    if isinstance(result, str):
        print("❌ Still Error:", result)
        print("\n💡 Try rephrasing your question")
    else:
        print(result.head(10))   # clean output

# ------------------ TEST ------------------

ask_agent("Top selling tracks")

"""MCP server"""

import sqlite3
import pandas as pd
from openai import OpenAI
from google.colab import userdata

# ------------------ API ------------------
client = OpenAI(
    api_key=userdata.get("SQL_KEY"),
    base_url="https://api.groq.com/openai/v1"
)

# ------------------ DATABASE ------------------
conn = sqlite3.connect("Chinook.db")   # <-- your uploaded file name

# ------------------ SQL TOOL ------------------
def sql_tool(query):
    try:
        df = pd.read_sql_query(query, conn)
        return df
    except Exception as e:
        return f"Error: {str(e)}"

# ------------------ AUTO TABLE DETECTION ------------------
def get_tables():
    tables = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table';"
    ).fetchall()
    return [t[0] for t in tables]

# ------------------ AUTO SCHEMA ------------------
def get_schema():
    schema = ""
    tables = get_tables()

    for table in tables:
        cols = conn.execute(f"PRAGMA table_info({table});").fetchall()
        schema += f"\nTable {table}: "
        for col in cols:
            schema += f"{col[1]}, "

    return schema

# ------------------ CLEAN SQL ------------------
def clean_sql(sql):
    sql = sql.replace("```", "")
    sql = sql.replace("sql", "")
    return sql.strip()

# ------------------ MCP GENERATE ------------------
def generate_mcp_response(question):
    schema = get_schema()
    tables = get_tables()

    prompt = f"""
You are a STRICT SQLite SQL generator.

IMPORTANT:
- Use ONLY these tables:
{tables}

- Use EXACT names (case sensitive)
- DO NOT change table names
- DO NOT invent tables
- DO NOT add 'sql'
- DO NOT explain anything

Schema:
{schema}

Question:
{question}

Return format:
TOOL: SQL_TOOL
QUERY: SELECT ...
"""

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content.strip()

# ------------------ PARSE ------------------
def parse_mcp_output(response):
    lines = response.split("\n")
    query = ""

    for line in lines:
        if "QUERY:" in line:
            query = line.replace("QUERY:", "").strip()

    return clean_sql(query)

# ------------------ FIX SQL ------------------
def fix_sql(query, error):
    schema = get_schema()
    tables = get_tables()

    prompt = f"""
Fix this SQL query.

IMPORTANT:
- Use ONLY these tables:
{tables}
- Use EXACT names
- DO NOT add 'sql'

Schema:
{schema}

Query:
{query}

Error:
{error}

Return ONLY corrected SQL.
"""

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    fixed = response.choices[0].message.content.strip()
    return clean_sql(fixed)

# ------------------ MCP AGENT ------------------
def mcp_agent(question):
    print("\n==============================")
    print(f"QUESTION: {question}")

    # Step 1: Generate MCP response
    response = generate_mcp_response(question)

    print("\n🔹 MCP Response:")
    print(response)

    # Step 2: Extract SQL
    sql = parse_mcp_output(response)

    print("\n🔹 SQL:")
    print(sql)

    # Step 3: Execute
    result = sql_tool(sql)

    # Step 4: Auto-fix if error
    if isinstance(result, str) and "Error" in result:
        print("\n⚠️ Fixing query...")

        fixed_sql = fix_sql(sql, result)

        print("\n🔹 Fixed SQL:")
        print(fixed_sql)

        result = sql_tool(fixed_sql)

    # Step 5: Output
    print("\n🔹 Result:\n")

    if isinstance(result, str):
        print("❌ Still Error:", result)
    else:
        print(result.head(10))

# ------------------ TEST ------------------

mcp_agent("Top selling tracks")

import sqlite3
import pandas as pd
from openai import OpenAI
from google.colab import userdata
import re

# ------------------ API ------------------
client = OpenAI(
    api_key=userdata.get("SQL_KEY"),
    base_url="https://api.groq.com/openai/v1"
)

# ------------------ DATABASE ------------------
conn = sqlite3.connect("Chinook.db")

# ------------------ GET TABLES ------------------
def get_tables():
    tables = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table';"
    ).fetchall()
    return [t[0] for t in tables]

# ------------------ GET SCHEMA ------------------
def get_schema():
    schema = ""
    tables = get_tables()

    for table in tables:
        cols = conn.execute(f"PRAGMA table_info({table});").fetchall()
        schema += f"\nTable {table}: "
        for col in cols:
            schema += f"{col[1]}, "
    return schema

# ------------------ CLEAN SQL ------------------
def clean_sql(sql):
    sql = sql.replace("```", "")
    sql = sql.replace("sql", "")
    return sql.strip()

# ------------------ EXTRACT TABLES FROM SQL ------------------
def extract_tables(sql):
    matches = re.findall(r'FROM\s+(\w+)|JOIN\s+(\w+)', sql, re.IGNORECASE)
    tables = []
    for m in matches:
        tables.extend([x for x in m if x])
    return tables

# ------------------ VALIDATE TABLES ------------------
def validate_sql(sql):
    actual_tables = [t.lower() for t in get_tables()]
    used_tables = [t.lower() for t in extract_tables(sql)]

    for t in used_tables:
        if t not in actual_tables:
            return False, t
    return True, None

# ------------------ SQL TOOL ------------------
def run_query(sql):
    try:
        df = pd.read_sql_query(sql, conn)
        return df
    except Exception as e:
        return f"Error: {str(e)}"

# ------------------ GENERATE SQL + EXPLANATION ------------------
def generate_sql_and_explanation(question):
    schema = get_schema()

    prompt = f"""
You are an expert SQLite agent.

STRICT RULES:
- Use ONLY tables from schema
- DO NOT invent tables
- DO NOT use words like sales unless present
- Generate VALID SQL
- Then explain it simply

Schema:
{schema}

User Question:
{question}

Return EXACT format:

SQL:
<SQL QUERY>

EXPLANATION:
<simple explanation of what query does>
"""

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    text = response.choices[0].message.content.strip()

    # Parse output
    sql = text.split("SQL:")[-1].split("EXPLANATION:")[0].strip()
    explanation = text.split("EXPLANATION:")[-1].strip()

    return clean_sql(sql), explanation

# ------------------ FIX SQL ------------------
def fix_sql(query, error):
    schema = get_schema()

    prompt = f"""
Fix this SQL query.

RULES:
- Use only tables from schema
- Do not invent tables
- Correct joins if needed

Schema:
{schema}

Query:
{query}

Error:
{error}

Return ONLY corrected SQL.
"""

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    return clean_sql(response.choices[0].message.content.strip())

# ------------------ FINAL AGENT ------------------
def smart_agent(question):
    print("\n==============================")
    print(f"QUESTION: {question}")

    # Step 1: Generate SQL + explanation
    sql, explanation = generate_sql_and_explanation(question)

    print("\n🔹 SQL:")
    print(sql)

    print("\n🔹 Explanation:")
    print(explanation)

    # Step 2: Validate tables BEFORE execution
    valid, wrong_table = validate_sql(sql)

    if not valid:
        print(f"\n⚠️ Invalid table detected: {wrong_table}")
        print("🔁 Regenerating query...")

        sql = fix_sql(sql, f"Invalid table: {wrong_table}")
        print("\n🔹 Fixed SQL:")
        print(sql)

    # Step 3: Execute query
    result = run_query(sql)

    # Step 4: If execution error → fix again
    if isinstance(result, str):
        print("\n⚠️ Execution error detected, fixing...")
        sql = fix_sql(sql, result)

        print("\n🔹 Fixed SQL:")
        print(sql)

        result = run_query(sql)

    # Step 5: Final Output
    print("\n🔹 Result:\n")

    if isinstance(result, str):
        print("❌ Still Error:", result)
    else:
        print(result.head(10))


# ------------------ TEST ------------------

smart_agent("Top tracks based on invoice_items quantity")

"""now we added the validation layer as it will chake the table if exist the only it will exicute

"""

import sqlite3

conn = sqlite3.connect("Chinook_Sqlite.sqlite")

tables = conn.execute(
    "SELECT name FROM sqlite_master WHERE type='table';"
).fetchall()

print("Tables:", tables)

"""NON MCP

User → LLM → SQL → Execute → Fix if needed → Result + Explanation
"""

import sqlite3
import pandas as pd
from openai import OpenAI
from google.colab import userdata

# ------------------ API ------------------
client = OpenAI(
    api_key=userdata.get("SQL_KEY"),
    base_url="https://api.groq.com/openai/v1"
)

# ------------------ DATABASE ------------------
conn = sqlite3.connect("Chinook_Sqlite.sqlite")

# ------------------ GET SCHEMA ------------------
def get_schema():
    schema = ""
    tables = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table';"
    ).fetchall()

    for t in tables:
        table = t[0]
        cols = conn.execute(f"PRAGMA table_info({table});").fetchall()
        schema += f"\nTable {table}: "
        for col in cols:
            schema += f"{col[1]}, "
    return schema

# ------------------ CLEAN SQL ------------------
def clean_sql(sql):
    return sql.replace("```", "").replace("sql", "").strip()

# ------------------ GENERATE SQL ------------------
def generate_sql(question):
    schema = get_schema()

    prompt = f"""
Generate SQLite query using ONLY this schema.
Do NOT invent tables.

Schema:
{schema}

Question:
{question}

Return ONLY SQL.
"""

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    return clean_sql(response.choices[0].message.content)

# ------------------ FIX SQL ------------------
def fix_sql(sql, error):
    schema = get_schema()

    prompt = f"""
Fix this SQL using schema.

Schema:
{schema}

Query:
{sql}

Error:
{error}

Return ONLY SQL.
"""

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    return clean_sql(response.choices[0].message.content)

# ------------------ SHORT EXPLANATION ------------------
def explain(sql):
    prompt = f"""
Explain in 1 line what this query does.

SQL:
{sql}
"""

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        temperature=0,
        max_tokens=25,
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content.strip()

# ------------------ RUN ------------------
def run_query(sql):
    try:
        return pd.read_sql_query(sql, conn)
    except Exception as e:
        return str(e)

# ------------------ MAIN ------------------
def agent(question):
    print("\n==============================")
    print("QUESTION:", question)

    sql = generate_sql(question)

    print("\n🔹 SQL:")
    print(sql)

    result = run_query(sql)

    if isinstance(result, str):
        print("\n⚠️ Fixing...")
        sql = fix_sql(sql, result)

        print("\n🔹 Fixed SQL:")
        print(sql)

        result = run_query(sql)

    print("\n🔹 Explanation:")
    print(explain(sql))

    print("\n🔹 Result:\n")
    print(result.head(10) if not isinstance(result, str) else result)

# ------------------ TEST ------------------

agent("Top selling tracks")

"""WITH MCP

User → LLM → Tool Decision → SQL Tool → Execute → Fix → Explain
"""

import sqlite3
import pandas as pd
from openai import OpenAI
from google.colab import userdata

# ------------------ API ------------------
client = OpenAI(
    api_key=userdata.get("SQL_KEY"),
    base_url="https://api.groq.com/openai/v1"
)

# ------------------ DATABASE ------------------
conn = sqlite3.connect("Chinook_Sqlite.sqlite")

# ------------------ GET SCHEMA ------------------
def get_schema():
    schema = ""
    tables = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table';"
    ).fetchall()

    for t in tables:
        table = t[0]
        cols = conn.execute(f"PRAGMA table_info({table});").fetchall()
        schema += f"\nTable {table}: "
        for col in cols:
            schema += f"{col[1]}, "
    return schema

# ------------------ SQL TOOL ------------------
def sql_tool(query):
    try:
        return pd.read_sql_query(query, conn)
    except Exception as e:
        return str(e)

# ------------------ CLEAN SQL ------------------
def clean_sql(sql):
    return sql.replace("```", "").replace("sql", "").strip()

# ------------------ MCP GENERATE ------------------
def generate_mcp(question):
    schema = get_schema()

    prompt = f"""
You are an AI SQL agent.

Use SQL_TOOL.

Rules:
- Use only tables from schema
- Do not invent tables
- Return EXACT format:

TOOL: SQL_TOOL
QUERY:
<SQL QUERY ONLY>

Schema:
{schema}

Question:
{question}
"""

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content

# ------------------ FIXED PARSE FUNCTION ------------------
def parse(response):
    if "QUERY:" not in response:
        return ""

    sql = response.split("QUERY:")[1]
    return clean_sql(sql)

# ------------------ FIX SQL ------------------
def fix_sql(sql, error):
    schema = get_schema()

    prompt = f"""
Fix SQL using schema.

Schema:
{schema}

Query:
{sql}

Error:
{error}

Return ONLY SQL.
"""

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    return clean_sql(response.choices[0].message.content)

# ------------------ SHORT EXPLANATION ------------------
def explain(sql):
    prompt = f"""
Explain in 1 line what this query does.

SQL:
{sql}
"""

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        temperature=0,
        max_tokens=25,
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content.strip()

# ------------------ MCP AGENT ------------------
def mcp_agent(question):
    print("\n==============================")
    print("QUESTION:", question)

    # Step 1: Generate MCP response
    response = generate_mcp(question)

    print("\n🔹 MCP Response:")
    print(response)

    # Step 2: Extract SQL
    sql = parse(response)

    if not sql:
        print("\n❌ Failed to extract SQL")
        return

    print("\n🔹 SQL:")
    print(sql)

    # Step 3: Execute SQL
    result = sql_tool(sql)

    # Step 4: Fix if error
    if isinstance(result, str):
        print("\n⚠️ Fixing...")
        sql = fix_sql(sql, result)

        print("\n🔹 Fixed SQL:")
        print(sql)

        result = sql_tool(sql)

    # Step 5: Explanation
    print("\n🔹 Explanation:")
    print(explain(sql))

    # Step 6: Output
    print("\n🔹 Result:\n")
    print(result.head(10) if not isinstance(result, str) else result)


# ------------------ TEST ------------------

mcp_agent("Top selling tracks")